### ISSUE TITLE
Save Address (Web)

### ISSUE THREAD

**Issue by literallyniki** [nyu-software-engineering/spring-2020-virtual-volcano#10]
As a user, I should be able to save specific addresses within my account as shortcuts to use when entering an address on the main page. 

**To Do:**

- If a user is logged in - hamburger should have Your Account (account settings), and Saved Location
- A user should be able to click the + and enter a specific address to save
- When the address is saved, a dialogue box saying "Address saved successfully" should appear.
- When a user later enters an address to the Midpoint main page, they should see the address on a list of "Saved Addresses" to choose from

**Comment by tiffanyhsu03** [comment]
1 point estimate
